Home page
Eliecer66/Movies-plus pull request #1
Opened 2023-03-28 18:13 UTC by Eliecer66

The home page section has as goal display the content of the page focusing on user interface experience. On the other hand the code has been  written taking into account the best practices and trying to follow a clean structure

2023-03-29 11:05 UTC, JorgEdmundo requested changes
Good work. Great progress. I see you are getting more confident in what you are doing. Then again these comments are for you to pay attention to the details.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/MoviesCarousel.js
> +    const setScore = (average) => {
Move this to a folder called `src/utils`, so you can use this method in multiple places.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/MoviesCarousel.js
> +    const movieList = () => {
This is a component. Create a component for the `MovieList`.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/MoviesCarousel.js
> +                <div className='movie--card'>
This `MovieCard` should also be a component.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/MoviesCarousel.js
> +                {data !== undefined && movieList()}
```suggestion
                {data && movieList()}
```

2023-03-29 11:05 UTC, JorgEdmundo commented on src/components/Carousel.js
> +    const fetchData = () => {
move this into a Custom Hook maybe in `src/hooks` so you can use it in different places.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/App.js
> +const API_KEY =  require('./utils');
use `import` and not `require`.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/components/HeaderCarousel.js
> +                return name != element.name ?
Recommendation, avoid using the ternary operator on `return`. Stick to using ternary operators on variable assignments.
Also, always use strict comparison `!==` instead of `!=`. Please read why.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/components/HeaderCarousel.js
> +                    className={item.isSelected === true ? 'selected': ''}
```suggestion
                    className={item.isSelected ? 'selected': ''}
```

2023-03-29 11:05 UTC, JorgEdmundo commented on src/components/PosterMovie.js
> +const IMAGE_PATH = 'https://image.tmdb.org/t/p/w220_and_h330_face/';
Move this into the util file.

2023-03-29 11:05 UTC, JorgEdmundo commented on src/styles/globals.scss
> +// NAVIGATION BAR SECTION
Break the styles for each component into its own file.

2023-03-29 20:35 UTC, JorgEdmundo requested changes
Making progress 💪

2023-03-29 20:35 UTC, JorgEdmundo commented on src/components/Carousel.js
> +const API_PATH = 'https://api.themoviedb.org/3/';
Move this to the utils file.

2023-03-29 20:35 UTC, JorgEdmundo commented on src/components/MovieList.js
> +const setScore = require('../utils/setScore');
Use `import`.

2023-03-29 20:35 UTC, JorgEdmundo commented on src/utils/setScore.js
> +module.exports = setScore;
```suggestion
export  {
  setScore
}
```

2023-03-29 20:35 UTC, JorgEdmundo commented on src/components/MovieList.js
> +                }
```suggestion
                score: setScore(average)
```

2023-03-29 20:35 UTC, JorgEdmundo commented on src/components/MovieList.js
> +                average: Math.round(item.vote_average * 10),
```suggestion
                average,
```

2023-03-29 20:35 UTC, JorgEdmundo commented on src/components/MovieList.js
> +        return data.results.map((item) => {
```suggestion
        return data.results.map((item) => {
          const average = Math.round(item.vote_average * 10);
```

2023-03-29 20:35 UTC, JorgEdmundo commented on src/components/MovieCard.js
> +                    score={movieData.score()}
Pass this prop as a string. Check the comment in the `MovieList` component.

2023-03-29 20:35 UTC, JorgEdmundo commented on src/components/MovieCard.js
> +                key={movieData.id}
Distructure `movieData`.

```suggestion
const { id, score, average, title, releaseDate, posterPath } = movieData;
```

2023-03-29 20:35 UTC, JorgEdmundo commented on src/utils/apiKey.js
> +export default apiKey;
Move this into one file, `utils/mdHelpers`.
```suggestion
const apiKey = '7c4a986b16b3b892bd7111a358d63e05';
const posterUrl = 'https://image.tmdb.org/t/p/w220_and_h330_face/';

export {
  apiKey,
  posterUrl
}
```

2023-03-29 20:35 UTC, JorgEdmundo commented on src/utils/posterUrl.js
> +const posterUrl = 'https://image.tmdb.org/t/p/w220_and_h330_face/';
See previous comment.

2023-03-29 20:35 UTC, JorgEdmundo commented on src/utils/setScore.js
> +    const goodRate = average > SCORE_PARAMETERS.GOOD;
These variables are booleans, name them as if they where answering a question, such as `isGoodRate`, and so on.

2023-03-29 20:35 UTC, JorgEdmundo commented on src/utils/setScore.js
> +    return rate;
```suggestion
    if (goodRate) return SCORE_PARAMETERS.HIGH;
    
    if (regularRate) return SCORE_PARAMETERS.MEDIUM;
    
    return SCORE_PARAMETERS.LOW;
```

2023-03-29 20:35 UTC, JorgEdmundo commented on src/utils/useFetch.js
> +const useFetch = (switchRoute) => {
Great! <3

2023-03-29 20:35 UTC, JorgEdmundo commented on src/App.js
>  import { render } from 'react-dom';
Delete unused dependencies.

2023-03-30 15:25 UTC, Eliecer66 commented on src/App.js
>  import { render } from 'react-dom';
Both dependencies are needed.

2023-03-30 17:49 UTC, JorgEdmundo requested changes
Just a tiny thing about the export/import. This way you will learn how and when to use `export default` and just `export`.

2023-03-30 17:49 UTC, JorgEdmundo commented on src/App.js
>  import { render } from 'react-dom';
Yes, you are right. Sorry I did not see that.

2023-03-30 17:49 UTC, JorgEdmundo commented on src/utils/apiUrls.js
> +export default apiUrls;
```suggestion
const domainName = 'https://api.themoviedb.org/3/',
const posterUrl = 'https://image.tmdb.org/t/p/w220_and_h330_face/',
const apiKey ='7c4a986b16b3b892bd7111a358d63e05'
export {
    domainName,
    posterUrl,
    apiKey
};
```

To use it on a file:

```suggestion
import {domainName} from '<path-to>/utils/apiUrls';
```

2023-03-31 15:08 UTC, ilGiorgio commented on src/utils/apiUrls.js
> +export default apiUrls;
I have read about the differences between `import` and `import default`, Now I have a good grasp about how those work. Thank you :1st_place_medal:

2023-03-31 15:15 UTC, merged